kind: pipeline
type: kubernetes
name: default

steps:
  # - name: build
  #   image: adoptopenjdk/openjdk11
  #   user: 0
  #   commands:
  #     - chmod +rwx ./mvnw
  #     - ./mvnw package -Dquarkus.package.type=fast-jar 
  # - name: docker
  #   image: plugins/docker
  #   settings:
  #     repo: modeseven/noticegen
  #     dockerfile: src/main/docker/Dockerfile.fast-jar
  #     tags:
  #       - ${DRONE_SOURCE_BRANCH/\//-}
  #       - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
  #     cache_from:
  #       - modeseven/noticegen:${DRONE_SOURCE_BRANCH/\//-}
  #     username:
  #       from_secret: dockerhub_username
  #     password:
  #       from_secret: dockerhub_password
  #   when:
  #     event:
  #       exclude:
  #         - tag


  - name: Update GITOPS
    image: cloudowski/drone-kustomize
    user: 0
    commands:
      - git version
      # - curl https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh --output kust.sh
      # - chmod +rwx ./kust.sh
      # - ls -l
      # - cat kust.sh
      #  - ./kust.sh
      - kustomize version
      - git clone https://github.com/modeseven/cluster.git
      - cd cluster/services/noticegen
      - ls -l
      # - cd deploy/overlays/dev    
      - kustomize edit set image modeseven/noticegen:${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      - ls -l
      - cat deployment.yml
      # - kubectl apply -k . && kubedog rollout track deployment {your-deployment-name} -n {your-namespace} -t {your-tomeout}
